
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fabián
 */
public class VentanaRegistroCivil extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRegistroCivil
     */
    public VentanaRegistroCivil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TextFieldNombre = new javax.swing.JTextField();
        TextFieldPrimerApellido = new javax.swing.JTextField();
        TextFieldSegundoApellido = new javax.swing.JTextField();
        TextFieldEdad = new javax.swing.JTextField();
        TextFieldCedula = new javax.swing.JTextField();
        TextFieldEstadoCivil = new javax.swing.JTextField();
        TextFieldFechaNacimiento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ComboBoxSexo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        TextFieldDomicilioElectoral = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TextFieldLugarNacimiento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ComboBoxFallecido = new javax.swing.JComboBox<>();
        TextFieldNacionalidad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1041, 558));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel2.setLayout(null);

        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(140, 80, 50, 20);

        jLabel3.setText("Primer apellido:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(110, 120, 80, 30);

        jLabel4.setText("Segundo apellido:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(100, 170, 90, 30);

        jLabel5.setText("Edad:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(160, 230, 40, 20);

        jLabel6.setText("Cédula:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(150, 270, 50, 30);

        jLabel7.setText("Estado civil:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(130, 320, 70, 30);

        jLabel8.setText("Fecha nacimiento:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(530, 80, 87, 15);

        TextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNombreActionPerformed(evt);
            }
        });
        jPanel2.add(TextFieldNombre);
        TextFieldNombre.setBounds(210, 70, 120, 28);
        jPanel2.add(TextFieldPrimerApellido);
        TextFieldPrimerApellido.setBounds(210, 120, 120, 28);
        jPanel2.add(TextFieldSegundoApellido);
        TextFieldSegundoApellido.setBounds(210, 170, 120, 26);

        TextFieldEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldEdadActionPerformed(evt);
            }
        });
        jPanel2.add(TextFieldEdad);
        TextFieldEdad.setBounds(210, 220, 120, 28);
        jPanel2.add(TextFieldCedula);
        TextFieldCedula.setBounds(210, 270, 120, 30);
        jPanel2.add(TextFieldEstadoCivil);
        TextFieldEstadoCivil.setBounds(210, 320, 120, 30);

        TextFieldFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldFechaNacimientoActionPerformed(evt);
            }
        });
        jPanel2.add(TextFieldFechaNacimiento);
        TextFieldFechaNacimiento.setBounds(630, 70, 118, 30);

        jLabel9.setText("Sexo:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(580, 130, 28, 15);

        ComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        jPanel2.add(ComboBoxSexo);
        ComboBoxSexo.setBounds(630, 120, 118, 24);

        jLabel10.setText("Lugar de nacimiento:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(510, 175, 110, 20);

        TextFieldDomicilioElectoral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldDomicilioElectoralActionPerformed(evt);
            }
        });
        jPanel2.add(TextFieldDomicilioElectoral);
        TextFieldDomicilioElectoral.setBounds(630, 320, 118, 31);

        jLabel11.setText("Nacionalidad:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(550, 230, 64, 15);

        TextFieldLugarNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldLugarNacimientoActionPerformed(evt);
            }
        });
        jPanel2.add(TextFieldLugarNacimiento);
        TextFieldLugarNacimiento.setBounds(630, 170, 118, 30);

        jLabel12.setText("Fallecido:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(560, 280, 45, 15);

        ComboBoxFallecido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        jPanel2.add(ComboBoxFallecido);
        ComboBoxFallecido.setBounds(630, 270, 118, 28);
        jPanel2.add(TextFieldNacionalidad);
        TextFieldNacionalidad.setBounds(630, 220, 120, 30);

        jLabel13.setText("Domicilio Electoral:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(520, 330, 90, 15);

        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(120, 430, 61, 25);

        jButton3.setText("Agregar ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(810, 200, 100, 50);

        jLabel15.setText("Agregar persona al registro civil");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(380, 0, 200, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);

        jLabel1.setText("Registro Civil");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(480, 20, 62, 15);

        jButton1.setText("Ir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 70, 40, 25);

        jLabel14.setText("Agregar  persona al registro civil:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(40, 70, 161, 15);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPanel2.setSize(1041, 558);
               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPanel2.setSize(0, 0);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TextFieldDomicilioElectoralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldDomicilioElectoralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldDomicilioElectoralActionPerformed

    private void TextFieldEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldEdadActionPerformed

    private void TextFieldFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldFechaNacimientoActionPerformed

    private void TextFieldLugarNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldLugarNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldLugarNacimientoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:      
        if(MetodosRegistroCivil.getInstance().buscarPersonaEmpadronada(Integer.parseInt(TextFieldCedula.getText())) == null){
            String n = TextFieldNombre.getText();
            String a1 = TextFieldPrimerApellido.getText();
            String a2 = TextFieldSegundoApellido.getText();
            int e = Integer.parseInt(TextFieldEdad.getText());
            int c = Integer.parseInt(TextFieldCedula.getText());
            String ec = TextFieldEstadoCivil.getText();
            String fn = TextFieldFechaNacimiento.getText();
            String sex = ComboBoxSexo.getSelectedItem().toString();
            String ln = TextFieldLugarNacimiento.getText();
            String nc = TextFieldNacionalidad.getText();
            boolean f = false;
            if(ComboBoxFallecido.getSelectedItem().equals("Sí")){
                f = true;  
            }
            String d = TextFieldDomicilioElectoral.getText();
            MetodosRegistroCivil.getInstance().agregarAlRegistro(n,a1,a2,e,c,ec,fn,sex,ln,nc,f,d);
            //nombre, primerApellido, segundoApellido, edad, cedula, estadoCivil, fechaNacimiento, sexo, lugarNacimiento, nacionalidad, fallecido, domicilioElectoral
    
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Ya existe una persona con la cédula: " + TextFieldCedula.getText());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistroCivil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxFallecido;
    private javax.swing.JComboBox<String> ComboBoxSexo;
    private javax.swing.JTextField TextFieldCedula;
    private javax.swing.JTextField TextFieldDomicilioElectoral;
    private javax.swing.JTextField TextFieldEdad;
    private javax.swing.JTextField TextFieldEstadoCivil;
    private javax.swing.JTextField TextFieldFechaNacimiento;
    private javax.swing.JTextField TextFieldLugarNacimiento;
    private javax.swing.JTextField TextFieldNacionalidad;
    private javax.swing.JTextField TextFieldNombre;
    private javax.swing.JTextField TextFieldPrimerApellido;
    private javax.swing.JTextField TextFieldSegundoApellido;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
