
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author toshib
 */
public class VentanaAgregarZona extends javax.swing.JFrame {
    VentanaElecciones ventanaPrincipal;
    private boolean navBar = false;
    public static int punteroProvincia = 0;
    public static int punteroCanton = 0;
    public static int punteroConsulado = 0;
    /**
     * Creates new form VentanaLogin
     */
    public VentanaAgregarZona(VentanaElecciones ventanaElecciones ) {
        this.ventanaPrincipal = ventanaPrincipal;
        initComponents();
        panelPrincipal.setSize(0,0);
    }   

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jButton24 = new javax.swing.JButton();
        nombreProvinciaTextField = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        codigoProvinciaTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        consuladoLabel = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        nombreLocalidadTextField = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        codigoLocalidadTextField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        nombreDistritoTextField = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        cantonLabel = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        codigoDistritoTextField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        nombreConsuladoTextField = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        codigoConsuladoTextField = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        provinciaLabel = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        nombreCantonTextField = new javax.swing.JTextField();
        jButton23 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        codigoCantonTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 0, 82));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addDocument.png"))); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(120, 100, 110, 120);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Agregar Zona");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(70, 290, 230, 40);

        jButton5.setBackground(new java.awt.Color(0, 0, 82));
        jButton5.setForeground(new java.awt.Color(0, 0, 82));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/yes.png"))); // NOI18N
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(160, 450, 50, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(250, 600, 44, 44);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registro Civil");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 600, 190, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 350, 700);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPrincipal.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aditNode.png"))); // NOI18N
        panelPrincipal.add(jLabel1);
        jLabel1.setBounds(520, 10, 110, 110);

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(null);

        jLabel51.setText("Código:");
        jPanel8.add(jLabel51);
        jLabel51.setBounds(20, 100, 40, 30);

        jLabel52.setText("Nombre:");
        jPanel8.add(jLabel52);
        jLabel52.setBounds(10, 50, 50, 30);

        jButton24.setText("Agregar provincia");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton24);
        jButton24.setBounds(10, 160, 180, 30);

        nombreProvinciaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProvinciaTextFieldActionPerformed(evt);
            }
        });
        jPanel8.add(nombreProvinciaTextField);
        nombreProvinciaTextField.setBounds(70, 50, 120, 30);

        jLabel37.setText("Agregar Provincia");
        jPanel8.add(jLabel37);
        jLabel37.setBounds(60, 0, 120, 15);

        codigoProvinciaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoProvinciaTextFieldActionPerformed(evt);
            }
        });
        jPanel8.add(codigoProvinciaTextField);
        codigoProvinciaTextField.setBounds(70, 100, 120, 30);

        panelPrincipal.add(jPanel8);
        jPanel8.setBounds(70, 240, 200, 200);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);

        jLabel41.setText("Código:");
        jPanel4.add(jLabel41);
        jLabel41.setBounds(20, 60, 40, 30);

        jLabel43.setText("Nombre:");
        jPanel4.add(jLabel43);
        jLabel43.setBounds(20, 20, 40, 30);

        consuladoLabel.setText("Consulado");
        jPanel4.add(consuladoLabel);
        consuladoLabel.setBounds(60, 120, 130, 30);

        jButton16.setText(">");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton16);
        jButton16.setBounds(10, 130, 40, 25);
        jPanel4.add(nombreLocalidadTextField);
        nombreLocalidadTextField.setBounds(70, 20, 120, 30);

        jButton20.setText("Agregar Localida");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton20);
        jButton20.setBounds(10, 160, 180, 30);

        jLabel38.setText("Agregar Localidad");
        jPanel4.add(jLabel38);
        jLabel38.setBounds(50, 0, 100, 15);

        jLabel6.setText("Seleccione consulado:");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 100, 120, 15);

        codigoLocalidadTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoLocalidadTextFieldActionPerformed(evt);
            }
        });
        jPanel4.add(codigoLocalidadTextField);
        codigoLocalidadTextField.setBounds(70, 60, 120, 30);

        panelPrincipal.add(jPanel4);
        jPanel4.setBounds(290, 20, 200, 200);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(null);

        jLabel45.setText("Código :");
        jPanel5.add(jLabel45);
        jLabel45.setBounds(20, 70, 40, 30);

        jLabel46.setText("Nombre :");
        jPanel5.add(jLabel46);
        jLabel46.setBounds(10, 30, 50, 30);
        jPanel5.add(nombreDistritoTextField);
        nombreDistritoTextField.setBounds(70, 30, 120, 30);

        jButton17.setText(">");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton17);
        jButton17.setBounds(10, 130, 40, 25);

        cantonLabel.setText("Cantón");
        jPanel5.add(cantonLabel);
        cantonLabel.setBounds(60, 130, 130, 30);

        jLabel50.setText("Seleccione Cantón:");
        jPanel5.add(jLabel50);
        jLabel50.setBounds(10, 110, 100, 20);

        jButton18.setText("Agregar Distrito");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton18);
        jButton18.setBounds(10, 160, 180, 30);

        jLabel35.setText("Agregar Distrito");
        jPanel5.add(jLabel35);
        jLabel35.setBounds(60, 0, 90, 20);
        jPanel5.add(codigoDistritoTextField);
        codigoDistritoTextField.setBounds(70, 70, 120, 30);

        panelPrincipal.add(jPanel5);
        jPanel5.setBounds(70, 460, 200, 200);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(null);

        jLabel40.setText("Código:");
        jPanel6.add(jLabel40);
        jLabel40.setBounds(10, 100, 50, 30);

        jLabel42.setText("Nombre:");
        jPanel6.add(jLabel42);
        jLabel42.setBounds(10, 50, 40, 30);

        jButton14.setText("Agregar Consulado");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton14);
        jButton14.setBounds(20, 160, 170, 30);
        jPanel6.add(nombreConsuladoTextField);
        nombreConsuladoTextField.setBounds(60, 50, 130, 30);

        jLabel39.setText("Agregar Consulado/País");
        jPanel6.add(jLabel39);
        jLabel39.setBounds(30, 0, 160, 15);
        jPanel6.add(codigoConsuladoTextField);
        codigoConsuladoTextField.setBounds(60, 100, 130, 30);

        panelPrincipal.add(jPanel6);
        jPanel6.setBounds(70, 20, 200, 200);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(null);

        jLabel48.setText("Código:");
        jPanel7.add(jLabel48);
        jLabel48.setBounds(20, 70, 50, 30);

        jLabel49.setText("Nombre:");
        jPanel7.add(jLabel49);
        jLabel49.setBounds(20, 30, 40, 30);

        provinciaLabel.setText("Provincia");
        jPanel7.add(provinciaLabel);
        provinciaLabel.setBounds(60, 130, 130, 30);

        jButton22.setText(">");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton22);
        jButton22.setBounds(10, 130, 40, 25);
        jPanel7.add(nombreCantonTextField);
        nombreCantonTextField.setBounds(70, 30, 120, 30);

        jButton23.setText("Agregar Cantón");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton23);
        jButton23.setBounds(10, 160, 180, 30);

        jLabel47.setText("Seleccione provincia:");
        jPanel7.add(jLabel47);
        jLabel47.setBounds(10, 110, 120, 15);

        jLabel36.setText("Agregar Cantón");
        jPanel7.add(jLabel36);
        jLabel36.setBounds(60, 0, 110, 15);

        codigoCantonTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoCantonTextFieldActionPerformed(evt);
            }
        });
        jPanel7.add(codigoCantonTextField);
        codigoCantonTextField.setBounds(70, 70, 120, 30);

        panelPrincipal.add(jPanel7);
        jPanel7.setBounds(290, 240, 200, 200);

        getContentPane().add(panelPrincipal);
        panelPrincipal.setBounds(350, 0, 650, 700);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TSE _Reg.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 10, 650, 160);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonCr.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 170, 650, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (navBar == true){                //If is open
            panelPrincipal.setSize(0, 0);   //the panel for new game will change to close 
            navBar = false;                 //it change the NavBar 2 status
            } 
        else{ //if navBar is close
            panelPrincipal.setSize(650,700);//the panel for new game will change to Open
            navBar = true;                    // it change the NavBar 2 status
           
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        VentanaElecciones vElecciones =new VentanaElecciones();
        vElecciones.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VentanaRegistroCivil ventanaRegistroCivil  =new VentanaRegistroCivil(this.ventanaPrincipal);
        ventanaRegistroCivil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        String nombreConsulado = MetodosRegistroCivil.getInstance().listaConsulados.get(punteroConsulado).nombre;
        consuladoLabel.setText(nombreConsulado);
        if (punteroConsulado + 1 > (MetodosRegistroCivil.getInstance().listaConsulados.size() - 1)) {
            punteroConsulado = 0;
        } else {
            punteroConsulado++;
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        if (codigoLocalidadTextField.getText().isEmpty() | nombreLocalidadTextField.getText().isEmpty() | consuladoLabel.getText().equals("Consulado")) {
            JOptionPane.showMessageDialog(rootPane, "Campo vacío.");
        }
        else if(MetodosRegistroCivil.getInstance().buscarLocalidad(nombreLocalidadTextField.getText()) != null){
            JOptionPane.showMessageDialog(rootPane, "Ya existe una localidad con ese nombre.");
        }
        else{
            int codigo = Integer.parseInt(codigoLocalidadTextField.getText());
            String nombre = nombreLocalidadTextField.getText();
            String nombreConsulado = consuladoLabel.getText();
            Consulado consulado = MetodosRegistroCivil.getInstance().buscarConsulado(nombreConsulado);
            Localidad nuevaLocalidad = new Localidad(codigo, nombre, consulado);
            MetodosRegistroCivil.getInstance().listaLocalidades.add(nuevaLocalidad);
            JOptionPane.showMessageDialog(rootPane, "Localidad agregada con éxito al sistema.");
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        String nombreProvincia = MetodosRegistroCivil.getInstance().listaCantones.get(punteroCanton).nombre;
        cantonLabel.setText(nombreProvincia);
        if (punteroCanton + 1 > (MetodosRegistroCivil.getInstance().listaCantones.size() - 1)) {
            punteroCanton = 0;
        } else {
            punteroCanton++;
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if(codigoDistritoTextField.getText().isEmpty() | nombreDistritoTextField.getText().isEmpty() | cantonLabel.getText().equals("Distrito")){
            JOptionPane.showMessageDialog(rootPane, "Campo vacío.");
        }
        else{
            int codigo = Integer.parseInt(codigoDistritoTextField.getText());
            String nombre = nombreDistritoTextField.getText();
            String nombreCanton = cantonLabel.getText();
            Canton canton = MetodosRegistroCivil.getInstance().buscarCanton(nombreCanton);
            Distrito nuevoDistrito = new Distrito(codigo, nombre, canton);
            MetodosRegistroCivil.getInstance().listaDistritos.add(nuevoDistrito);
            JOptionPane.showMessageDialog(rootPane, "Distrito: " + nombre + " agregado con éxito al sistema.");
        }

    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        if (codigoConsuladoTextField.getText().isEmpty() | nombreConsuladoTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Campo vacío.");
        }
        else if(MetodosRegistroCivil.getInstance().buscarConsulado(nombreConsuladoTextField.getText()) != null){
            JOptionPane.showMessageDialog(rootPane, "Ya existe un consulado con ese nombre.");
        }
        else {
            int codigo = Integer.parseInt(codigoConsuladoTextField.getText());
            String nombre = nombreConsuladoTextField.getText();
            Consulado nuevoConsulado = new Consulado(nombre, codigo);
            MetodosRegistroCivil.getInstance().listaConsulados.add(nuevoConsulado);
            JOptionPane.showMessageDialog(rootPane, "Consulado/País: " + nombre + " agregado con éxito al sistema.");
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        String nombreProvincia = MetodosRegistroCivil.getInstance().listaProvincias.get(punteroProvincia).nombre;
        provinciaLabel.setText(nombreProvincia);
        if(punteroProvincia + 1 > ( MetodosRegistroCivil.getInstance().listaProvincias.size() - 1 )){
            punteroProvincia = 0;
        }
        else{
            punteroProvincia++;
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void codigoCantonTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoCantonTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoCantonTextFieldActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        if(codigoCantonTextField.getText().isEmpty() | nombreCantonTextField.getText().isEmpty() | provinciaLabel.getText().equals("Provincia")){
            JOptionPane.showMessageDialog(rootPane, "Campo vacío.");
        }
        else if(MetodosRegistroCivil.getInstance().buscarCanton(nombreCantonTextField.getText()) != null){
            JOptionPane.showMessageDialog(rootPane, "Ya existe un cantón con ese nombre.");
        }
        else{
            int codigo = Integer.parseInt(codigoCantonTextField.getText());
            String nombre = nombreCantonTextField.getText();
            Provincia provincia = MetodosRegistroCivil.getInstance().buscarProvincia(provinciaLabel.getText());
            Canton nuevoCanton = new Canton(codigo, nombre, provincia);
            MetodosRegistroCivil.getInstance().listaCantones.add(nuevoCanton);
            JOptionPane.showMessageDialog(rootPane, "Cantón: " + nombre + " agregado con éxito al sistema.");
        }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void codigoProvinciaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoProvinciaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoProvinciaTextFieldActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        if(codigoProvinciaTextField.getText().isEmpty() | nombreProvinciaTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Campo vacío.");
        }
        else if(MetodosRegistroCivil.getInstance().buscarProvincia(nombreProvinciaTextField.getText()) != null){
            JOptionPane.showMessageDialog(rootPane, "Ya existe una provincia con ese nombre.");
        }
        else{
            int codigo = Integer.parseInt(codigoProvinciaTextField.getText());
            String nombre = nombreProvinciaTextField.getText();
            Provincia nuevaProvincia = new Provincia(codigo, nombre);
            MetodosRegistroCivil.getInstance().listaProvincias.add(nuevaProvincia);
            JOptionPane.showMessageDialog(rootPane, "Provincia: " + nombre + " agregada al sistema.");
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void nombreProvinciaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreProvinciaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreProvinciaTextFieldActionPerformed

    private void codigoLocalidadTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoLocalidadTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoLocalidadTextFieldActionPerformed
    public void cerrar() {
        VentanaRegistroCivil ventanaRegistro = new VentanaRegistroCivil(this.ventanaPrincipal);
        ventanaRegistro.setVisible(true);
        this.dispose();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantonLabel;
    private javax.swing.JTextField codigoCantonTextField;
    private javax.swing.JTextField codigoConsuladoTextField;
    private javax.swing.JTextField codigoDistritoTextField;
    private javax.swing.JTextField codigoLocalidadTextField;
    private javax.swing.JTextField codigoProvinciaTextField;
    private javax.swing.JLabel consuladoLabel;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField nombreCantonTextField;
    private javax.swing.JTextField nombreConsuladoTextField;
    private javax.swing.JTextField nombreDistritoTextField;
    private javax.swing.JTextField nombreLocalidadTextField;
    private javax.swing.JTextField nombreProvinciaTextField;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel provinciaLabel;
    // End of variables declaration//GEN-END:variables
}
