
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author toshib
 */
public class VentanaConsultarResultado extends javax.swing.JFrame {
    VentanaElecciones ventanaPrincipal;
    private boolean navBar = false;
    /**
     * Creates new form VentanaLogin
     */
    public VentanaConsultarResultado(VentanaElecciones ventanaElecciones ) {
        this.ventanaPrincipal = ventanaPrincipal;
        initComponents();
        panelPrincipal.setSize(0,0);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        consultarDireccionTextField = new javax.swing.JTextField();
        distritoTextField = new javax.swing.JTextField();
        provinciaTextField = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        cantonTextField = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        localidadTextField = new javax.swing.JTextField();
        consuladoTextField = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        partidoTextField = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        partidoTextField1 = new javax.swing.JTextField();
        partidoTextField2 = new javax.swing.JTextField();
        partidoTextField3 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 0, 82));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sear.png"))); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(120, 100, 110, 120);

        jButton5.setBackground(new java.awt.Color(0, 0, 82));
        jButton5.setForeground(new java.awt.Color(0, 0, 82));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/yes.png"))); // NOI18N
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(150, 430, 50, 50);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Consultas");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(50, 270, 250, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(250, 600, 44, 44);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Menu Principal");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(40, 600, 190, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 350, 700);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPrincipal.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Search Property_100px.png"))); // NOI18N
        panelPrincipal.add(jLabel1);
        jLabel1.setBounds(120, 10, 110, 110);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel14.setText("18 y 40 años");
        panelPrincipal.add(jLabel14);
        jLabel14.setBounds(40, 320, 180, 40);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel19.setText("Consultar dirección por ID");
        panelPrincipal.add(jLabel19);
        jLabel19.setBounds(0, 120, 310, 40);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel20.setText("Votantes +100 años");
        panelPrincipal.add(jLabel20);
        jLabel20.setBounds(0, 210, 230, 40);

        jButton4.setBackground(new java.awt.Color(0, 0, 82));
        jButton4.setForeground(new java.awt.Color(0, 0, 82));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/searchB.png"))); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton4);
        jButton4.setBounds(240, 160, 40, 40);

        jButton6.setBackground(new java.awt.Color(0, 0, 82));
        jButton6.setForeground(new java.awt.Color(0, 0, 82));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/searchB.png"))); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton6);
        jButton6.setBounds(240, 530, 40, 40);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel22.setText("Votos por género");
        panelPrincipal.add(jLabel22);
        jLabel22.setBounds(10, 250, 200, 40);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel25.setText("Consulado");
        panelPrincipal.add(jLabel25);
        jLabel25.setBounds(10, 630, 120, 40);

        jButton11.setBackground(new java.awt.Color(0, 0, 82));
        jButton11.setForeground(new java.awt.Color(0, 0, 82));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/searchB.png"))); // NOI18N
        jButton11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton11);
        jButton11.setBounds(240, 210, 40, 40);

        jButton12.setBackground(new java.awt.Color(0, 0, 82));
        jButton12.setForeground(new java.awt.Color(0, 0, 82));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/searchB.png"))); // NOI18N
        jButton12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton12);
        jButton12.setBounds(240, 260, 40, 40);

        jButton13.setBackground(new java.awt.Color(0, 0, 82));
        jButton13.setForeground(new java.awt.Color(0, 0, 82));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/searchB.png"))); // NOI18N
        jButton13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton13);
        jButton13.setBounds(240, 310, 40, 40);

        jButton15.setBackground(new java.awt.Color(0, 0, 82));
        jButton15.setForeground(new java.awt.Color(0, 0, 82));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/searchB.png"))); // NOI18N
        jButton15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton15);
        jButton15.setBounds(240, 430, 40, 40);
        panelPrincipal.add(consultarDireccionTextField);
        consultarDireccionTextField.setBounds(10, 160, 220, 40);
        panelPrincipal.add(distritoTextField);
        distritoTextField.setBounds(130, 430, 100, 40);
        panelPrincipal.add(provinciaTextField);
        provinciaTextField.setBounds(130, 530, 100, 40);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel26.setText("Partido Político");
        panelPrincipal.add(jLabel26);
        jLabel26.setBounds(380, 220, 190, 40);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel27.setText("Cantón");
        panelPrincipal.add(jLabel27);
        jLabel27.setBounds(380, 430, 100, 40);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel28.setText("Distrito");
        panelPrincipal.add(jLabel28);
        jLabel28.setBounds(380, 330, 100, 40);
        panelPrincipal.add(cantonTextField);
        cantonTextField.setBounds(130, 480, 100, 40);

        jButton7.setBackground(new java.awt.Color(0, 0, 82));
        jButton7.setForeground(new java.awt.Color(0, 0, 82));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/searchB.png"))); // NOI18N
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton7);
        jButton7.setBounds(240, 480, 40, 40);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel15.setText("Votantes entre  ");
        panelPrincipal.add(jLabel15);
        jLabel15.setBounds(20, 300, 180, 40);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel29.setText("Provincia");
        panelPrincipal.add(jLabel29);
        jLabel29.setBounds(380, 530, 110, 40);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel30.setText("Localidad");
        panelPrincipal.add(jLabel30);
        jLabel30.setBounds(10, 580, 110, 40);
        panelPrincipal.add(localidadTextField);
        localidadTextField.setBounds(130, 580, 100, 40);
        panelPrincipal.add(consuladoTextField);
        consuladoTextField.setBounds(130, 630, 100, 40);

        jButton8.setBackground(new java.awt.Color(0, 0, 82));
        jButton8.setForeground(new java.awt.Color(0, 0, 82));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/searchB.png"))); // NOI18N
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton8);
        jButton8.setBounds(240, 630, 40, 40);

        jButton9.setBackground(new java.awt.Color(0, 0, 82));
        jButton9.setForeground(new java.awt.Color(0, 0, 82));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/searchB.png"))); // NOI18N
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton9);
        jButton9.setBounds(240, 580, 40, 40);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel31.setText("Numero de votantes por:");
        panelPrincipal.add(jLabel31);
        jLabel31.setBounds(10, 370, 340, 40);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel32.setText("Cantidad de votos");
        panelPrincipal.add(jLabel32);
        jLabel32.setBounds(360, 110, 230, 40);
        panelPrincipal.add(partidoTextField);
        partidoTextField.setBounds(380, 260, 170, 40);

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel33.setText("Distrito");
        panelPrincipal.add(jLabel33);
        jLabel33.setBounds(10, 430, 100, 40);

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel34.setText("Cantón");
        panelPrincipal.add(jLabel34);
        jLabel34.setBounds(10, 480, 100, 40);

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel35.setText("Provincia");
        panelPrincipal.add(jLabel35);
        jLabel35.setBounds(10, 530, 110, 40);

        jButton10.setBackground(new java.awt.Color(0, 0, 82));
        jButton10.setForeground(new java.awt.Color(0, 0, 82));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/searchB.png"))); // NOI18N
        jButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton10);
        jButton10.setBounds(510, 470, 40, 40);

        jButton14.setBackground(new java.awt.Color(0, 0, 82));
        jButton14.setForeground(new java.awt.Color(0, 0, 82));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/searchB.png"))); // NOI18N
        jButton14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton14);
        jButton14.setBounds(510, 370, 40, 40);

        jButton16.setBackground(new java.awt.Color(0, 0, 82));
        jButton16.setForeground(new java.awt.Color(0, 0, 82));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/searchB.png"))); // NOI18N
        jButton16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton16);
        jButton16.setBounds(510, 570, 40, 40);
        panelPrincipal.add(partidoTextField1);
        partidoTextField1.setBounds(380, 370, 120, 40);
        panelPrincipal.add(partidoTextField2);
        partidoTextField2.setBounds(380, 470, 120, 40);
        panelPrincipal.add(partidoTextField3);
        partidoTextField3.setBounds(380, 570, 120, 40);

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel36.setText("por partido en:");
        panelPrincipal.add(jLabel36);
        jLabel36.setBounds(370, 150, 210, 40);

        getContentPane().add(panelPrincipal);
        panelPrincipal.setBounds(350, 0, 0, 700);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/consul.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 250, 310, 210);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(350, 0, 650, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (navBar == true){                //If is open
            panelPrincipal.setSize(0, 0);   //the panel for new game will change to close 
            navBar = false;                 //it change the NavBar 2 status
            } 
        else{ //if navBar is close
            panelPrincipal.setSize(650,700);//the panel for new game will change to Open
            navBar = true;                    // it change the NavBar 2 status
           
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(consultarDireccionTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Digite un ID a buscar");
        }
        else{
            Persona aux = MetodosRegistroCivil.getInstance().buscarPersonaEmpadronada(Integer.parseInt(consultarDireccionTextField.getText()));
            if (aux != null) {
                if (aux.domicilioElectoral.getDistrito() != null) {
                    String direccion = "Lugar de votación: " + aux.domicilioElectoral.nombre + ", Distrito: " + aux.domicilioElectoral.getDistrito().nombre + ", Cantón: " + aux.domicilioElectoral.getDistrito().canton.nombre + ", Provincia: " + aux.domicilioElectoral.getDistrito().canton.provincia.nombre;
                    JOptionPane.showMessageDialog(rootPane, direccion);
                } 
                else if (aux.domicilioElectoral.getLocalidad() != null) {
                    String direccion2 = "Lugar de votación: " + aux.domicilioElectoral.nombre + ", Localidad: " + aux.domicilioElectoral.getLocalidad().nombre + ", consulado: " + aux.domicilioElectoral.getLocalidad().consulado.nombre;
                    JOptionPane.showMessageDialog(rootPane, direccion2);
                }
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "No se encuentra la persona con el ID digitado.");
            }      
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(provinciaTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Digite una provincia a buscar.");
        }
        else{
            Provincia d = MetodosRegistroCivil.getInstance().buscarProvincia(provinciaTextField.getText());
            if(d != null){
                int cantidadDeVotantes = MetodosRegistroCivil.getInstance().consultarVotosPresidentePorProvincia(d.nombre);
                JOptionPane.showMessageDialog(rootPane, "Cantidad de votos en la provincia " + d.nombre + ": " + cantidadDeVotantes);
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "La provincia digitada no existe.");
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        int cantidadCentenarios = MetodosRegistroCivil.getInstance().obtenerVotantesCentenarios();
        JOptionPane.showMessageDialog(rootPane, "Cantidad de votantes mayores a 100 años: " + cantidadCentenarios);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        int n;
        int m;
        n = MetodosRegistroCivil.getInstance().obtenerCantidadHombres();
        m = MetodosRegistroCivil.getInstance().obtenerCantidadMujeres();
        JOptionPane.showMessageDialog(rootPane,n + " total de hombres, " + m + " total de mujeres.");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        int cantidadAdultos = MetodosRegistroCivil.getInstance().obtenerVotantesAdultos();
        JOptionPane.showMessageDialog(rootPane, "Cantidad de votantes entre 18 y 40 años: " + cantidadAdultos);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        if(distritoTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Digite un distrito a buscar");
        }
        else{
            Distrito d = MetodosRegistroCivil.getInstance().buscarDistrito(distritoTextField.getText());
            if(d != null){
                int cantidadDeVotantes = MetodosRegistroCivil.getInstance().consultarVotosPresidentePorDistrito(d.nombre);
                JOptionPane.showMessageDialog(rootPane, "Cantidad de votos" + d.nombre + ": " + cantidadDeVotantes);
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "El distrito digitado no existe");
            }
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cerrar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        VentanaElecciones vElecciones =new VentanaElecciones();
        vElecciones.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(cantonTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Digite un canton a buscar");
        }
        else{
            Canton d = MetodosRegistroCivil.getInstance().buscarCanton(cantonTextField.getText());
            if(d != null){
                int cantidadDeVotantes = MetodosRegistroCivil.getInstance().consultarVotosPresidentePorCanton(d.nombre);
                JOptionPane.showMessageDialog(rootPane, "Cantidad de votantes en el cantón " + d.nombre + ": " + cantidadDeVotantes);
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "El cantón digitado no existe");
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(consuladoTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Digite un consulado a buscar.");
        }
        else{
            Localidad d = MetodosRegistroCivil.getInstance().buscarLocalidad(consuladoTextField.getText());
            if(d != null){
                int cantidadDeVotantes = MetodosRegistroCivil.getInstance().consultarVotosPresidentePorConsulado(d.nombre);
                JOptionPane.showMessageDialog(rootPane, "Cantidad de votantes en el consulado " + d.nombre + ": " + cantidadDeVotantes);
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Consulado digitado no existe.");
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed
    
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(localidadTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Digite una localidad a buscar");
        }
        else{
            Localidad d = MetodosRegistroCivil.getInstance().buscarLocalidad(localidadTextField.getText());
            if(d != null){
                int cantidadDeVotantes = MetodosRegistroCivil.getInstance().consultarVotosPresidentePorLocalidad(d.nombre);
                JOptionPane.showMessageDialog(rootPane, "Cantidad de votantes en la localidad " + d.nombre + ": " + cantidadDeVotantes);
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Localidad digitada no existe");
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if(partidoTextField.getText().isEmpty() | partidoTextField2.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Campo vacío");
        }
        else{
            PartidoPolitico pp = MetodosRegistroCivil.getInstance().buscarPartidoPolitico(partidoTextField.getText());
            Canton dp = MetodosRegistroCivil.getInstance().buscarCanton(partidoTextField2.getText());
            if(pp != null && dp != null){
                int cant = MetodosRegistroCivil.getInstance().consultarVotosPartidoPorCanton(pp.nombre, dp.nombre);
                JOptionPane.showMessageDialog(rootPane, "Cantidad de votos al partido politico: " + pp.nombre + " en el canton:" + dp.nombre + "es igual a: " + cant);
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Partido politico/canton no encontrado.");
            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
       // TODO add your handling code here:
        if(partidoTextField.getText().isEmpty() | partidoTextField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Campo vacío");
        }
        else{
            PartidoPolitico pp = MetodosRegistroCivil.getInstance().buscarPartidoPolitico(partidoTextField.getText());
            Distrito dp = MetodosRegistroCivil.getInstance().buscarDistrito(partidoTextField1.getText());
            if(pp != null && dp != null){
                int cant = MetodosRegistroCivil.getInstance().consultarVotosPartidoPorProvincia(pp.nombre, dp.nombre);
                JOptionPane.showMessageDialog(rootPane, "Cantidad de votos al partido politico: " + pp.nombre + " en el distrito:" + dp.nombre + "es igual a: " + cant);
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Partido politico/distrito no encontrado.");
            }
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        if(partidoTextField.getText().isEmpty() | partidoTextField3.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Campo vacío");
        }
        else{
            PartidoPolitico pp = MetodosRegistroCivil.getInstance().buscarPartidoPolitico(partidoTextField.getText());
            Provincia dp = MetodosRegistroCivil.getInstance().buscarProvincia(partidoTextField3.getText());
            if(pp != null && dp != null){
                int cant = MetodosRegistroCivil.getInstance().consultarVotosPartidoPorDistrito(pp.nombre, dp.nombre);
                JOptionPane.showMessageDialog(rootPane, "Cantidad de votos al partido politico: " + pp.nombre + " en la provincia: " + dp.nombre + "es igual a: " + cant);
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Partido politico/provincia no encontrado.");
            }
        }
    }//GEN-LAST:event_jButton16ActionPerformed
    public void cerrar() {
        VentanaElecciones ventanaElecciones = new VentanaElecciones();
        ventanaElecciones.setVisible(true);
        this.dispose();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantonTextField;
    private javax.swing.JTextField consuladoTextField;
    private javax.swing.JTextField consultarDireccionTextField;
    private javax.swing.JTextField distritoTextField;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField localidadTextField;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField partidoTextField;
    private javax.swing.JTextField partidoTextField1;
    private javax.swing.JTextField partidoTextField2;
    private javax.swing.JTextField partidoTextField3;
    private javax.swing.JTextField provinciaTextField;
    // End of variables declaration//GEN-END:variables
}
