
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author toshib
 */
public class VentanaAgregarMiembroDeMesa extends javax.swing.JFrame {
    VentanaElecciones ventanaPrincipal;
    public static int punteroJRV = 0;
    public static int punteroPersona = 0;
    public static int punteroPartidoPolitico = 0;
    private boolean navBar = false;
    /**
     * Creates new form VentanaLogin
     */
    public VentanaAgregarMiembroDeMesa(VentanaElecciones ventanaElecciones ) {
        this.ventanaPrincipal = ventanaPrincipal;
        initComponents();
        panelPrincipal.setSize(0,0);
    }   

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();
        panelPrincipal1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        labelPartidoPolitico = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        labelJRV = new javax.swing.JLabel();
        labelPersona = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 0, 82));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addUser.png"))); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(120, 100, 110, 120);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Miembro de Mesa");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(40, 340, 310, 40);

        jButton5.setBackground(new java.awt.Color(0, 0, 82));
        jButton5.setForeground(new java.awt.Color(0, 0, 82));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/yes.png"))); // NOI18N
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(160, 450, 50, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(250, 600, 44, 44);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registro Civil");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 600, 190, 40);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Agregar ");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(110, 280, 150, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 350, 700);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPrincipal.setLayout(null);

        panelPrincipal1.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPrincipal1.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addList.png"))); // NOI18N
        panelPrincipal1.add(jLabel6);
        jLabel6.setBounds(520, 10, 110, 110);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel8.setText("Función:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 180, 50, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Miembro", "Fiscal", "Auxiliar Electoral" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(140, 180, 110, 30);

        jButton1.setText(">>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(50, 130, 50, 30);

        labelPartidoPolitico.setText("Partido Político");
        jPanel1.add(labelPartidoPolitico);
        labelPartidoPolitico.setBounds(140, 130, 90, 30);

        jButton6.setText(">>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(50, 80, 50, 30);

        jButton4.setText(">>");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(50, 30, 50, 30);

        labelJRV.setText("JRV ");
        jPanel1.add(labelJRV);
        labelJRV.setBounds(110, 30, 200, 30);

        labelPersona.setText("Persona");
        jPanel1.add(labelPersona);
        labelPersona.setBounds(140, 80, 50, 30);

        jButton7.setText("+ Miembro de Mesa");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(50, 240, 210, 30);

        panelPrincipal1.add(jPanel1);
        jPanel1.setBounds(80, 200, 330, 310);

        panelPrincipal.add(panelPrincipal1);
        panelPrincipal1.setBounds(0, 0, 1000, 700);

        getContentPane().add(panelPrincipal);
        panelPrincipal.setBounds(350, 0, 650, 700);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TSE _Reg.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 10, 650, 160);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonCr.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 170, 650, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (navBar == true){                //If is open
            panelPrincipal.setSize(0, 0);   //the panel for new game will change to close 
            navBar = false;                 //it change the NavBar 2 status
            } 
        else{ //if navBar is close
            panelPrincipal.setSize(650,700);//the panel for new game will change to Open
            navBar = true;                    // it change the NavBar 2 status
           
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        VentanaElecciones vElecciones =new VentanaElecciones();
        vElecciones.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VentanaRegistroCivil ventanaRegistroCivil  =new VentanaRegistroCivil(this.ventanaPrincipal);
        ventanaRegistroCivil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String nombrePersona = MetodosRegistroCivil.getInstance().listaPersonasEmpadronadas.get(punteroPersona).nombre;
        labelPersona.setText(nombrePersona);
        if (punteroPersona + 1 > (MetodosRegistroCivil.getInstance().listaPersonasEmpadronadas.size() - 1)) {
            punteroPersona = 0;
        } else {
            punteroPersona++;
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(labelJRV.getText().equals("JRV") | labelPersona.getText().equals("Persona") | labelPartidoPolitico.getText().equals("Partido Político")){
            JOptionPane.showMessageDialog(rootPane, "Campo vacío");
        }
        else{
            JRVExtranjera jrve = MetodosRegistroCivil.getInstance().buscarJRVExtranjera(labelJRV.getText());
            JRVNacional jrvn = MetodosRegistroCivil.getInstance().buscarJRVNacional(labelJRV.getText());
            Persona miembro = MetodosRegistroCivil.getInstance().buscarPersonaEmpadronadaNombre(labelPersona.getText());
            if (jrve != null) {
                if (MetodosRegistroCivil.getInstance().buscarMiembroDeMesaJRVE(jrve, miembro.nombre) != null) {
                    JOptionPane.showMessageDialog(rootPane, "Ya existe ese miembro de mesa en la JRV seleccionada.");      
                }
                else{
                    String jrv = labelJRV.getText();
                    Persona persona = MetodosRegistroCivil.getInstance().buscarPersonaEmpadronadaNombre(labelPersona.getText());
                    String funcion = jComboBox1.getSelectedItem().toString();
                    PartidoPolitico partidoPolitico = MetodosRegistroCivil.getInstance().buscarPartidoPolitico(labelPartidoPolitico.getText());
                    MiembroDeMesa nuevoMiembroDeMesa = new MiembroDeMesa(persona, funcion, partidoPolitico);
                    MetodosRegistroCivil.getInstance().agregarMiembroDeMesaExtranjero(jrv, nuevoMiembroDeMesa);
                    JOptionPane.showMessageDialog(rootPane, "Miembro de mesa agregado con éxito a la JRV Extranjera: " + jrv);
                }
            } 
            else if (jrvn != null) {
                if(MetodosRegistroCivil.getInstance().buscarMiembroDeMesaJRVN(jrvn, miembro.nombre) != null){
                    JOptionPane.showMessageDialog(rootPane, "Ya existe ese miembro de mesa en la JRV seleccionada."); 
                }
                else{
                    String jrv = labelJRV.getText();
                    Persona persona = MetodosRegistroCivil.getInstance().buscarPersonaEmpadronadaNombre(labelPersona.getText());
                    String funcion = jComboBox1.getSelectedItem().toString();
                    PartidoPolitico partidoPolitico = MetodosRegistroCivil.getInstance().buscarPartidoPolitico(labelPartidoPolitico.getText());
                    MiembroDeMesa nuevoMiembroDeMesa = new MiembroDeMesa(persona, funcion, partidoPolitico);
                    MetodosRegistroCivil.getInstance().agregarMiembroDeMesaNacional(jrv, nuevoMiembroDeMesa);
                    JOptionPane.showMessageDialog(rootPane, "Miembro de mesa agregado con éxito a la JRV nacional: " + jrv);
                }

            }
        }
        
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      String nombrePartidoPolitico = MetodosRegistroCivil.getInstance().listaPartidosPoliticos.get(punteroPartidoPolitico).nombre;
        labelPartidoPolitico.setText(nombrePartidoPolitico);
        if (punteroPartidoPolitico + 1 > (MetodosRegistroCivil.getInstance().listaPartidosPoliticos.size() - 1)) {
            punteroPartidoPolitico = 0;
        } else {
            punteroPartidoPolitico++;
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String nombreJRV = MetodosRegistroCivil.getInstance().listaTotalJRV.get(punteroJRV).getCentroVotacion();
        labelJRV.setText(nombreJRV);
        if (punteroJRV + 1 > (MetodosRegistroCivil.getInstance().listaTotalJRV.size() - 1)) {
            punteroJRV = 0;
        } else {
            punteroJRV++;
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    public void cerrar() {
        VentanaRegistroCivil ventanaRegistro = new VentanaRegistroCivil(this.ventanaPrincipal);
        ventanaRegistro.setVisible(true);
        this.dispose();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelJRV;
    private javax.swing.JLabel labelPartidoPolitico;
    private javax.swing.JLabel labelPersona;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelPrincipal1;
    // End of variables declaration//GEN-END:variables
}
